### PR TITLE
[YOLOv7] Bug fixes for MaxPool's pad

### PR DESCRIPTION
**Pull request by PINTO0309**
### 1. Content and background
YOLOv7-tiny output results do not match.
https://github.com/triptec/detection-models/blob/master/yolov7/yolov7-tiny.onnx

- onnx2tf
[model_float32.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/10137612/model_float32.tflite.zip)

- compare tflite
[yolov7-tiny.tflite.zip](https://github.com/PINTO0309/onnx2tf/files/10137609/yolov7-tiny.tflite.zip)

Input Data
zidane

The correct output is shown in the figure below.
image

### 2. Summary of corrections

Test Code
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
import numpy as np
from pprint import pprint
np.random.seed(0)

import cv2

dummy_input = cv2.imread('zidane.jpg')
dummy_input = cv2.resize(dummy_input, [640,640])
dummy_input = dummy_input.astype(np.float32)[np.newaxis, ...]

# onnx2tf
interpreter = tf.lite.Interpreter('onnx2tf/saved_model/model_float32.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.set_tensor(input_details[0]['index'], dummy_input)
interpreter.invoke()
ret1 = interpreter.get_tensor(output_details[0]['index'])
pprint(ret1)

# Float32
interpreter = tf.lite.Interpreter('onnx2tf/saved_model/yolov7-tiny.tflite')
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
interpreter.set_tensor(input_details[0]['index'], dummy_input)
interpreter.invoke()
ret2 = interpreter.get_tensor(output_details[0]['index'])
pprint(ret2)

ret2 = ret2.transpose(0,2,1)

print(f'total ret1: {ret1.flatten().shape}, ret2: {ret2.flatten().shape}')
print(f'total isclose ret1-ret2: {np.isclose(ret1.flatten(), ret2.flatten()).all()}')
```

Results
```
total ret1: (2142000,), ret2: (2142000,)
total isclose ret1-ret2: True
```
### 3. Before/After (If there is an operating log that can be used as a reference)
.

### 4. Issue number (only if there is a related issue)
[Yolov7 problem with detection coordinates #34](https://github.com/PINTO0309/onnx2tf/issues/34)

### CODE REVIEW

**Comment by triptec** [comment]
Where or how did you get the yolov7-tiny.tflite? Have you been able to run any detection with that model and had it produce correct coordinates for the boxes?

**Comment by PINTO0309** [comment]
Please use this one.
https://github.com/MPolaris/onnx2tflite

I just used the detect.py you shared.

**Comment by triptec** [comment]
when you used onnx2tflite, what flags did you use?
Because I still get maxed out boxes like
```
tensor([2.38769e+05, 1.02938e+05, 3.69561e+05, 3.17340e+05, 7.93247e-01, 0.00000e+00])
tensor([1.40133e+05, 2.27762e+05, 1.72790e+05, 3.18102e+05, 5.84962e-01, 2.70000e+01])
tensor([4.17281e+04, 1.53941e+05, 3.06352e+05, 3.16274e+05, 5.76938e-01, 0.00000e+00])
[tensor(1280.), tensor(720.), tensor(1280.), tensor(720.)] tensor(0.57694) tensor(0.)
[tensor(1280.), tensor(720.), tensor(1280.), tensor(720.)] tensor(0.58496) tensor(27.)
[tensor(1280.), tensor(720.), tensor(1280.), tensor(720.)] tensor(0.79325) tensor(0.)

```

**Comment by PINTO0309** [comment]
The output is an exact match.
```python
import os
os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
import tensorflow as tf
import numpy as np
from pprint import pprint
np.random.seed(0)
np.set_printoptions(linewidth=np.inf)

import cv2

dummy_input = cv2.imread('zidane.jpg')
dummy_input = cv2.resize(dummy_input, [640,640])
dummy_input = dummy_input.astype(np.float32)[np.newaxis, ...]

# onnx2tf
interpreter1 = tf.lite.Interpreter('onnx2tf/saved_model/model_float32.tflite')
interpreter1.allocate_tensors()
input_details1 = interpreter1.get_input_details()
output_details1 = interpreter1.get_output_details()
interpreter1.set_tensor(input_details1[0]['index'], dummy_input)
interpreter1.invoke()
ret1 = interpreter1.get_tensor(output_details1[0]['index'])
pprint(ret1)

# Float32
interpreter2 = tf.lite.Interpreter('onnx2tf/saved_model/yolov7-tiny.tflite')
interpreter2.allocate_tensors()
input_details2 = interpreter2.get_input_details()
output_details2 = interpreter2.get_output_details()
interpreter2.set_tensor(input_details2[0]['index'], dummy_input)
interpreter2.invoke()
ret2 = interpreter2.get_tensor(output_details2[0]['index'])
pprint(ret2)

ret2 = ret2.transpose(0,2,1)

print(f'total ret1: {ret1.shape}, ret2: {ret2.shape}')
print(f'total isclose ret1-ret2: {np.allclose(ret1, ret2)}')

judge = True
for idx, (i, j) in enumerate(zip(ret1[0], ret2[0])):
    print(i)
    print(j)
    judge = judge and np.array_equal(i, j)
print(judge)
```
```
[6.0641534e+02 6.1236951e+02 1.6331400e+02 1.3524472e+02 3.2027103e-05 1.9017691e-04 1.7531438e-08 6.6372580e-05 3.3952503e-05 1.2810221e-04 4.4987850e-05 1.4887646e-06 1.4806140e-05 1.2055146e-05 3.9054416e-05 4.2189985e-08 2.9351320e-06 1.9786443e-05 3.5291126e-07 3.8266339e-06 2.6931319e-09 4.2873407e-09 1.7889413e-06 3.7182858e-08 4.2167438e-09 2.8954338e-08 4.2399083e-08 1.0670997e-09 7.8064133e-10 3.6127421e-05 2.4610670e-06 7.4970512e-07 4.3963686e-05 8.3320901e-06 1.5925878e-05 1.2727010e-03 7.6454104e-05 4.8349237e-05 1.2158165e-04 1.5327684e-04 1.4104902e-06 1.0158599e-05 6.1516971e-03 4.1893878e-04 4.2137151e-07 2.1775545e-06 1.7678691e-07 2.5381301e-05 4.9773239e-06 1.9157262e-06 1.6136516e-07 3.7686730e-06 9.9540330e-06 1.1612757e-07 3.0136100e-06 2.0390307e-06 3.4868199e-07 3.0710243e-07 2.4173041e-10 3.1184475e-06 9.8668545e-07 5.8028778e-08 4.2700559e-09 6.3314857e-08 6.6934298e-08 1.6327940e-05 4.4057324e-05 6.5111199e-05 8.2899518e-05 2.7510310e-05 1.3091564e-05 6.7147853e-06 2.5193444e-02 5.4171454e-07 2.2227052e-08 8.3073992e-06 9.3198352e-08 5.7469117e-07 3.9677734e-06 1.5550482e-05 2.4703760e-07 1.0821618e-04 6.3032417e-08 1.9672496e-05 3.4515320e-05]

[6.0641534e+02 6.1236951e+02 1.6331400e+02 1.3524472e+02 3.2027103e-05 1.9017691e-04 1.7531438e-08 6.6372580e-05 3.3952503e-05 1.2810221e-04 4.4987850e-05 1.4887646e-06 1.4806140e-05 1.2055146e-05 3.9054416e-05 4.2189985e-08 2.9351320e-06 1.9786443e-05 3.5291126e-07 3.8266339e-06 2.6931319e-09 4.2873407e-09 1.7889413e-06 3.7182858e-08 4.2167438e-09 2.8954338e-08 4.2399083e-08 1.0670997e-09 7.8064133e-10 3.6127421e-05 2.4610670e-06 7.4970512e-07 4.3963686e-05 8.3320901e-06 1.5925878e-05 1.2727010e-03 7.6454104e-05 4.8349237e-05 1.2158165e-04 1.5327684e-04 1.4104902e-06 1.0158599e-05 6.1516971e-03 4.1893878e-04 4.2137151e-07 2.1775545e-06 1.7678691e-07 2.5381301e-05 4.9773239e-06 1.9157262e-06 1.6136516e-07 3.7686730e-06 9.9540330e-06 1.1612757e-07 3.0136100e-06 2.0390307e-06 3.4868199e-07 3.0710243e-07 2.4173041e-10 3.1184475e-06 9.8668545e-07 5.8028778e-08 4.2700559e-09 6.3314857e-08 6.6934298e-08 1.6327940e-05 4.4057324e-05 6.5111199e-05 8.2899518e-05 2.7510310e-05 1.3091564e-05 6.7147853e-06 2.5193444e-02 5.4171454e-07 2.2227052e-08 8.3073992e-06 9.3198352e-08 5.7469117e-07 3.9677734e-06 1.5550482e-05 2.4703760e-07 1.0821618e-04 6.3032417e-08 1.9672496e-05 3.4515320e-05]

True
```

**Comment by PINTO0309** [comment]
This is the only option I specified because there are no meaningful conversion options.
```
python converter.py --weights yolov7-tiny.onnx
```

**Comment by triptec** [comment]
Ok. Because I haven't gotten that model to work either. That's why I asked.

**Comment by triptec** [comment]
https://github.com/MPolaris/onnx2tflite/issues/25

**Comment by PINTO0309** [comment]
The following comments appear to have been submitted.
```
The output's format is channel last(1, 85, 25200), not channel first like onnx or pytorch (1, 25200, 85). It maybe make error.
```

I am comparing the last output by transposing it.
```python
ret2 = ret2.transpose(0,2,1)
```

**Comment by triptec** [comment]
yeah I saw that. So when I use transpose on on the output from onnx2tflite I get the same result as I get with onnx2tf.
Ie it detects the correct labels but I can't figure out why the coordinates of the boxes isn't correct.

**Comment by PINTO0309** [comment]
I am a little confused too, using yolov5's detect.py does not detect it correctly.

**Comment by triptec** [comment]
I FOUND IT!
yolov5 does a "y[0][..., :4] *= [w, h, w, h]  # xywh normalized to pixels" (https://github.com/ultralytics/yolov5/blob/master/models/common.py#L581)
If I comment that out it works!

what can I do your you to show my appreciation!?

**Comment by PINTO0309** [comment]
Thank you. Please give me a pull request for something when you feel up to it. I am happy with that. :smile:

**Comment by PINTO0309** [comment]
Haha. That was right.
zidane

**Comment by triptec** [comment]
Well I'll see what I can do about that PR, I don't find it likely I'm going to find a bug that I can solve in your repos but if I do I'm surely going to make a PR. Thank you again.

**Pull request merged**
