### PR TITLE
Created If operation

### PR DESCRIPTION
**Pull request by timatom**
### 1. Content and background

I'm working on converting a pre-trained (with COCO2017) SSDLite MobileNet V3 in pytorch to ONNX and then to TensorFlow. However, while converting from ONNX to TensorFlow, a missing `If` operation prevented me from completing the conversion.

### 2. Summary of corrections

I created an If operation using tf.cond along with directions from the [Contribution Guide](https://github.com/PINTO0309/onnx2tf/blob/main/CONTRIBUTING.md).

I can provide the onnx model on request. The param_replacement.json is as follows:
```json
{
    "format_version": 1,
    "operations": 
    [
      {
        "op_name": "/transform/Sub",
        "param_target": "inputs",
        "param_name": "/transform/Constant_output_0",
        "pre_process_transpose_perm": [1, 2, 0]
      },
      {
        "op_name": "/transform/Div",
        "param_target": "inputs",
        "param_name": "/transform/Constant_output_0",
        "pre_process_transpose_perm": [1, 2, 0]
      }
    ]
}
```

### 3. Before/After (If there is an operating log that can be used as a reference)

Before:
```
ERROR: If OP is not yet implemented.
```

After:
```INFO: onnx_op_type: If onnx_op_name: If_3462
INFO:  input_name.1: onnx::Cast_4102 shape: [] dtype: bool
INFO:  output_name.1: onnx::Slice_4104 shape: ['unk__780'] dtype: int64
INFO: tf_op_type: cond_for_tf_v2
INFO:  input.1.x: name: tf.math.equal/Equal:0 shape: () dtype: <dtype: 'bool'> 
INFO:  output.1.output: name: tf.math.equal/Equal:0 shape: () dtype: <dtype: 'bool'>```

### CODE REVIEW

**Comment by PINTO0309** [comment]
I would be very happy if you could compress the ONNX file to ZIP and attach it to this pull request or upload it to Google Drive here. After the file is retrieved, the drive link is deactivated.
- timatom
  https://drive.google.com/drive/u/0/folders/13P8K78PWcSOxPjCqpzsXTQJVS9nmkSAb

**Comment by PINTO0309** [comment]
If possible, your revised proposal would be perfect if it could handle `IF` syntax, including the following subgraphs

https://github.com/PINTO0309/onnx2tf/blob/main/make_test_op/make_If.py

https://github.com/PINTO0309/onnx2tf/blob/main/make_test_op/ops/If_p1_11.onnx
https://github.com/PINTO0309/onnx2tf/blob/main/make_test_op/ops/If_p2_11.onnx
https://github.com/PINTO0309/onnx2tf/blob/main/make_test_op/ops/If_p3_11.onnx

The current proposed fix is that all `IF` OP output will be of type Boolean.

- e.g.
  - sample onnx
    image
  - Conversion result by your `IF` OP
    image

**Comment by timatom** [comment]
I'll continue working on revising the PR to include syntax, namely one which can handle the subgraphs you've shared.

tf.cond does not directly work with KerasTensor objects, so it may take me a few days.

**Comment by PINTO0309** [comment]
IF OP of nested structure is now supported. https://github.com/PINTO0309/onnx2tf/releases/tag/1.3.8

Therefore, I am sorry, but I am canceling this pull request. Other pull requests are always welcome. :smile:

**Pull request closed without merging**
