### PR TITLE
Supports parameter substitution for post-processing of `Conv`

### PR DESCRIPTION
**Pull request by PINTO0309**
### 1. Content and background
- `Conv`
  - Supports parameter substitution for post-processing of `Conv`
  - replace_conv.json
    ```json
    {
      "format_version": 1,
      "operations": [
        {
          "op_name": "wa/conv/Conv",
          "param_target": "outputs",
          "param_name": "output",
          "post_process_transpose_perm": [0,3,1,2]
        }
      ]
    }
    ```
  - test
    ```
    onnx2tf -i model_conv.onnx -kat input -prf replace_conv.json
    ```
    image

### 4. Issue number (only if there is a related issue)
- [Add transposition to the tflite model #700](https://github.com/PINTO0309/onnx2tf/issues/700)

### CODE REVIEW

**Comment by marcoschepis** [comment]
Is this the possiblity to add our own weights after the quantization?

**Comment by PINTO0309** [comment]
No. The `-prf` option only does simple tensor transposition or some other OP substitutions. onnx2tf does not have the ability to add weights. I think adding weights when converting a model with onnx2tf is beyond the scope of the tool's responsibility.

Therefore, it is better to process ONNX files directly.
https://github.com/ZhangGe6/onnx-modifier
https://github.com/PINTO0309/simple-onnx-processing-tools

**Comment by marcoschepis** [comment]
Ah thank you, the problem is that when you modify the ONNX and than convert it in tflite, the weights get changed automatically. I was trying to find a way to have the weights I want in the tflite.

**Comment by marcoschepis** [comment]
Thank you very much, you've been so much helpful

**Comment by marcoschepis** [comment]
> Since the quantization flow is only provided via the TFLiteConverter API, you will likely need to rewrite the Flatbuffer directly after quantization to achieve what you want.

Sorry to bother you again, I wasn't able to find how to implement the modification of a onnx or tflite via the flatbuffers as you suggested. Cen you explain better? Thank you very much in advance.

**Comment by PINTO0309** [comment]
here
https://github.com/PINTO0309/onnx2tf/blob/67d5b4c94bef576270e32b5b214f7f8cfcdb57d9/onnx2tf/utils/common_functions.py#L4541

**Comment by marcoschepis** [comment]
this function writes the operations name, i would like to modify the weights of a layer

**Pull request merged**
